// vocabulary.ts - Contains vocabulary words for language learning

// Sample vocabulary words for language learning
export const VOCABULARY_WORDS = [
  { word: "apple", meaning: "a round fruit", difficulty: 1 },
  { word: "arm", meaning: "part of the body", difficulty: 1 },
  { word: "baby", meaning: "a very young child", difficulty: 1 },
  { word: "ball", meaning: "a round object used in games", difficulty: 1 },
  { word: "bed", meaning: "furniture for sleeping", difficulty: 1 },
  { word: "bee", meaning: "a flying insect", difficulty: 1 },
  { word: "bird", meaning: "an animal with feathers", difficulty: 1 },
  { word: "book", meaning: "a set of written pages", difficulty: 1 },
  { word: "box", meaning: "a container", difficulty: 1 },
  { word: "boy", meaning: "a male child", difficulty: 1 },
  { word: "car", meaning: "a road vehicle", difficulty: 1 },
  { word: "cat", meaning: "a small domesticated carnivorous mammal", difficulty: 1 },
  { word: "chair", meaning: "a seat", difficulty: 1 },
  { word: "child", meaning: "a young human being", difficulty: 1 },
  { word: "city", meaning: "a large town", difficulty: 1 },
  { word: "cold", meaning: "low temperature", difficulty: 1 },
  { word: "come", meaning: "to move toward", difficulty: 1 },
  { word: "cook", meaning: "to prepare food", difficulty: 1 },
  { word: "cow", meaning: "a large farm animal", difficulty: 1 },
  { word: "cup", meaning: "a small bowl-shaped container", difficulty: 1 },
  { word: "day", meaning: "24 hours", difficulty: 1 },
  { word: "dog", meaning: "a domesticated carnivorous mammal", difficulty: 1 },
  { word: "door", meaning: "a movable barrier", difficulty: 1 },
  { word: "ear", meaning: "the organ of hearing", difficulty: 1 },
  { word: "eat", meaning: "to consume food", difficulty: 1 },
  { word: "egg", meaning: "an oval object laid by birds", difficulty: 1 },
  { word: "eye", meaning: "the organ of sight", difficulty: 1 },
  { word: "face", meaning: "the front part of the head", difficulty: 1 },
  { word: "farm", meaning: "land used to grow crops or animals", difficulty: 1 },
  { word: "father", meaning: "a male parent", difficulty: 1 },
  { word: "fish", meaning: "an aquatic animal", difficulty: 1 },
  { word: "flower", meaning: "the seed-bearing part of a plant", difficulty: 1 },
  { word: "food", meaning: "substance eaten to maintain life", difficulty: 1 },
  { word: "foot", meaning: "the lower extremity of the leg", difficulty: 1 },
  { word: "friend", meaning: "a person whom one knows and likes", difficulty: 1 },
  { word: "fun", meaning: "enjoyment or amusement", difficulty: 1 },
  { word: "girl", meaning: "a female child", difficulty: 1 },
  { word: "go", meaning: "to move", difficulty: 1 },
  { word: "good", meaning: "having desirable qualities", difficulty: 1 },
  { word: "grass", meaning: "vegetation consisting of short plants", difficulty: 1 },
  { word: "hand", meaning: "the end part of a person's arm", difficulty: 1 },
  { word: "hat", meaning: "a head covering", difficulty: 1 },
  { word: "head", meaning: "the upper part of the body", difficulty: 1 },
  { word: "hear", meaning: "to perceive sound", difficulty: 1 },
  { word: "hill", meaning: "a naturally raised area of land", difficulty: 1 },
  { word: "home", meaning: "where one lives", difficulty: 1 },
  { word: "horse", meaning: "a large animal used for riding", difficulty: 1 },
  { word: "house", meaning: "a building for human habitation", difficulty: 1 },
  { word: "ice", meaning: "frozen water", difficulty: 1 },
  { word: "in", meaning: "expressing the situation of something", difficulty: 1 },
  { word: "jump", meaning: "to push oneself off a surface", difficulty: 1 },
  { word: "key", meaning: "a device used to open locks", difficulty: 1 },
  { word: "king", meaning: "a male ruler", difficulty: 1 },
  { word: "kite", meaning: "a light frame flown in the wind", difficulty: 1 },
  { word: "lamp", meaning: "a device for giving light", difficulty: 1 },
  { word: "leg", meaning: "each of the limbs on which a person or animal walks", difficulty: 1 },
  { word: "man", meaning: "an adult male human", difficulty: 1 },
  { word: "map", meaning: "a visual representation of an area", difficulty: 1 },
  { word: "milk", meaning: "a white liquid produced by mammals", difficulty: 1 },
  { word: "moon", meaning: "the Earth's natural satellite", difficulty: 1 },
  { word: "mother", meaning: "a female parent", difficulty: 1 },
  { word: "mouse", meaning: "a small rodent", difficulty: 1 },
  { word: "mouth", meaning: "the opening in the face used for eating", difficulty: 1 },
  { word: "name", meaning: "a word by which a person or thing is known", difficulty: 1 },
  { word: "nose", meaning: "the part of the face used for smelling", difficulty: 1 },
  { word: "pen", meaning: "an instrument for writing", difficulty: 1 },
  { word: "pig", meaning: "a farm animal", difficulty: 1 },
  { word: "play", meaning: "to engage in activity for enjoyment", difficulty: 1 },
  { word: "rain", meaning: "water falling from the sky", difficulty: 1 },
  { word: "red", meaning: "a color", difficulty: 1 },
  { word: "river", meaning: "a large natural stream of water", difficulty: 1 },
  { word: "road", meaning: "a wide way leading from one place to another", difficulty: 1 },
  { word: "run", meaning: "to move quickly on foot", difficulty: 1 },
  { word: "sea", meaning: "a large body of salt water", difficulty: 1 },
  { word: "see", meaning: "to perceive with the eyes", difficulty: 1 },
  { word: "shoe", meaning: "footwear", difficulty: 1 },
  { word: "shop", meaning: "a place to buy things", difficulty: 1 },
  { word: "sing", meaning: "to produce musical tones with the voice", difficulty: 1 },
  { word: "sit", meaning: "to rest with the body supported by the buttocks", difficulty: 1 },
  { word: "sky", meaning: "the expanse of air over the Earth", difficulty: 1 },
  { word: "snow", meaning: "frozen precipitation", difficulty: 1 },
  { word: "star", meaning: "a luminous point in the night sky", difficulty: 1 },
  { word: "sun", meaning: "the star at the center of our solar system", difficulty: 1 },
  { word: "table", meaning: "a piece of furniture with a flat top", difficulty: 1 },
  { word: "toy", meaning: "an object for a child to play with", difficulty: 1 },
  { word: "train", meaning: "a series of connected vehicles running on a track", difficulty: 1 },
  { word: "tree", meaning: "a perennial plant with an elongated stem", difficulty: 1 },
  { word: "water", meaning: "a colorless liquid essential for life", difficulty: 1 },
  { word: "window", meaning: "an opening in a wall to admit light", difficulty: 1 },
  { word: "woman", meaning: "an adult female human", difficulty: 1 },
  { word: "yellow", meaning: "a color", difficulty: 1 },
  { word: "achieve", meaning: "to successfully reach a goal", difficulty: 2 },
  { word: "active", meaning: "engaging or ready to engage in physically energetic pursuits", difficulty: 2 },
  { word: "advice", meaning: "guidance or recommendations", difficulty: 2 },
  { word: "allow", meaning: "to permit", difficulty: 2 },
  { word: "amount", meaning: "quantity of something", difficulty: 2 },
  { word: "angry", meaning: "feeling or showing anger", difficulty: 2 },
  { word: "animal", meaning: "a living organism that feeds on organic matter", difficulty: 2 },
  { word: "appear", meaning: "to come into sight", difficulty: 2 },
  { word: "arrive", meaning: "to reach a place", difficulty: 2 },
  { word: "artist", meaning: "a person who creates art", difficulty: 2 },
  { word: "attack", meaning: "to take aggressive action", difficulty: 2 },
  { word: "attention", meaning: "notice taken of someone or something", difficulty: 2 },
  { word: "beautiful", meaning: "pleasing to the senses", difficulty: 2 },
  { word: "begin", meaning: "to start", difficulty: 2 },
  { word: "believe", meaning: "to accept as true", difficulty: 2 },
  { word: "benefit", meaning: "an advantage or profit", difficulty: 2 },
  { word: "borrow", meaning: "to take and use temporarily", difficulty: 2 },
  { word: "bother", meaning: "to annoy or worry", difficulty: 2 },
  { word: "brave", meaning: "showing courage", difficulty: 2 },
  { word: "build", meaning: "to construct", difficulty: 2 },
  { word: "busy", meaning: "actively doing something", difficulty: 2 },
  { word: "carry", meaning: "to support and move something", difficulty: 2 },
  { word: "cause", meaning: "a person or thing that brings about an effect", difficulty: 2 },
  { word: "celebrate", meaning: "to mark an occasion with festivities", difficulty: 2 },
  { word: "center", meaning: "the middle point", difficulty: 2 },
  { word: "chance", meaning: "a possibility of something happening", difficulty: 2 },
  { word: "change", meaning: "to make or become different", difficulty: 2 },
  { word: "charge", meaning: "to demand payment", difficulty: 2 },
  { word: "choose", meaning: "to select", difficulty: 2 },
  { word: "clean", meaning: "free from dirt", difficulty: 2 },
  { word: "climb", meaning: "to go upward", difficulty: 2 },
  { word: "collect", meaning: "to gather together", difficulty: 2 },
  { word: "compare", meaning: "to note the similarity or difference", difficulty: 2 },
  { word: "complete", meaning: "having all necessary parts", difficulty: 2 },
  { word: "consider", meaning: "to think carefully about", difficulty: 2 },
  { word: "continue", meaning: "to keep going", difficulty: 2 },
  { word: "control", meaning: "the power to influence", difficulty: 2 },
  { word: "correct", meaning: "free from error", difficulty: 2 },
  { word: "cover", meaning: "to put something over", difficulty: 2 },
  { word: "create", meaning: "to bring into existence", difficulty: 2 },
  { word: "cry", meaning: "to shed tears", difficulty: 2 },
  { word: "danger", meaning: "the possibility of harm", difficulty: 2 },
  { word: "decide", meaning: "to make a choice", difficulty: 2 },
  { word: "describe", meaning: "to give an account of", difficulty: 2 },
  { word: "design", meaning: "to create a plan for", difficulty: 2 },
  { word: "destroy", meaning: "to ruin completely", difficulty: 2 },
  { word: "develop", meaning: "to grow or cause to grow", difficulty: 2 },
  { word: "different", meaning: "not the same", difficulty: 2 },
  { word: "difficult", meaning: "needing much effort", difficulty: 2 },
  { word: "direction", meaning: "the path along which something moves", difficulty: 2 },
  { word: "discover", meaning: "to find out", difficulty: 2 },
  { word: "discuss", meaning: "to talk about", difficulty: 2 },
  { word: "distance", meaning: "the amount of space between two points", difficulty: 2 },
  { word: "divide", meaning: "to separate into parts", difficulty: 2 },
  { word: "doubt", meaning: "a feeling of uncertainty", difficulty: 2 },
  { word: "draw", meaning: "to produce a picture", difficulty: 2 },
  { word: "dream", meaning: "a series of thoughts during sleep", difficulty: 2 },
  { word: "drive", meaning: "to operate a vehicle", difficulty: 2 },
  { word: "drop", meaning: "to let something fall", difficulty: 2 },
  { word: "early", meaning: "before the expected time", difficulty: 2 },
  { word: "easy", meaning: "not difficult", difficulty: 2 },
  { word: "educate", meaning: "to give knowledge", difficulty: 2 },
  { word: "effect", meaning: "a result", difficulty: 2 },
  { word: "effort", meaning: "a vigorous attempt", difficulty: 2 },
  { word: "empty", meaning: "containing nothing", difficulty: 2 },
  { word: "encourage", meaning: "to give support", difficulty: 2 },
  { word: "enjoy", meaning: "to take delight in", difficulty: 2 },
  { word: "enter", meaning: "to go into", difficulty: 2 },
  { word: "escape", meaning: "to get free", difficulty: 2 },
  { word: "evening", meaning: "the time after sunset", difficulty: 2 },
  { word: "event", meaning: "an occurrence", difficulty: 2 },
  { word: "exact", meaning: "completely correct", difficulty: 2 },
  { word: "excite", meaning: "to cause strong feelings", difficulty: 2 },
  { word: "exercise", meaning: "physical activity for health", difficulty: 2 },
  { word: "expect", meaning: "to think something will happen", difficulty: 2 },
  { word: "experience", meaning: "practical contact with events", difficulty: 2 },
  { word: "explain", meaning: "to make something clear", difficulty: 2 },
  { word: "express", meaning: "to convey a thought", difficulty: 2 },
  { word: "face", meaning: "the front part of a person's head", difficulty: 2 },
  { word: "fail", meaning: "to not succeed", difficulty: 2 },
  { word: "fair", meaning: "free from bias", difficulty: 2 },
  { word: "fall", meaning: "to drop down", difficulty: 2 },
  { word: "famous", meaning: "known by many people", difficulty: 2 },
  { word: "fast", meaning: "moving quickly", difficulty: 2 },
  { word: "fear", meaning: "an unpleasant emotion", difficulty: 2 },
  { word: "feel", meaning: "to experience an emotion or sensation", difficulty: 2 },
  { word: "fight", meaning: "to take part in a violent struggle", difficulty: 2 },
  { word: "fill", meaning: "to make full", difficulty: 2 },
  { word: "abundant", meaning: "existing or occurring in large amounts", difficulty: 3 },
  { word: "adapt", meaning: "to adjust to new conditions", difficulty: 3 },
  { word: "adverse", meaning: "preventing success or development; harmful", difficulty: 3 },
  { word: "advocate", meaning: "to publicly support or recommend", difficulty: 3 },
  { word: "ambiguous", meaning: "open to more than one interpretation", difficulty: 3 },
  { word: "ambitious", meaning: "having a strong desire for success or achievement", difficulty: 3 },
  { word: "analogy", meaning: "a comparison between two things", difficulty: 3 },
  { word: "analyze", meaning: "to examine in detail", difficulty: 3 },
  { word: "anxious", meaning: "experiencing worry or nervousness", difficulty: 3 },
  { word: "apprehensive", meaning: "anxious or fearful about the future", difficulty: 3 },
  { word: "approximate", meaning: "close to the actual, but not exact", difficulty: 3 },
  { word: "arbitrary", meaning: "based on random choice or personal whim", difficulty: 3 },
  { word: "assert", meaning: "to state a fact confidently", difficulty: 3 },
  { word: "assess", meaning: "to evaluate or estimate", difficulty: 3 },
  { word: "astonish", meaning: "to surprise greatly", difficulty: 3 },
  { word: "attain", meaning: "to achieve or reach", difficulty: 3 },
  { word: "attribute", meaning: "a quality regarded as a characteristic", difficulty: 3 },
  { word: "authentic", meaning: "genuine or real", difficulty: 3 },
  { word: "authorize", meaning: "to give official permission", difficulty: 3 },
  { word: "beneficial", meaning: "resulting in good; favorable", difficulty: 3 },
  { word: "bias", meaning: "prejudice in favor of or against something", difficulty: 3 },
  { word: "bizarre", meaning: "very strange or unusual", difficulty: 3 },
  { word: "calculate", meaning: "to determine mathematically", difficulty: 3 },
  { word: "candid", meaning: "truthful and straightforward", difficulty: 3 },
  { word: "capacity", meaning: "the ability to hold or contain", difficulty: 3 },
  { word: "category", meaning: "a class or division of things", difficulty: 3 },
  { word: "cease", meaning: "to bring or come to an end", difficulty: 3 },
  { word: "challenge", meaning: "a task or situation that tests abilities", difficulty: 3 },
  { word: "clarify", meaning: "to make something clearer", difficulty: 3 },
  { word: "coherent", meaning: "logical and consistent", difficulty: 3 },
  { word: "collapse", meaning: "to fall down or give way", difficulty: 3 },
  { word: "colleague", meaning: "a person one works with", difficulty: 3 },
  { word: "commence", meaning: "to begin or start", difficulty: 3 },
  { word: "commit", meaning: "to pledge or bind to a certain course", difficulty: 3 },
  { word: "compel", meaning: "to force someone to do something", difficulty: 3 },
  { word: "competent", meaning: "having the necessary ability or skill", difficulty: 3 },
  { word: "compile", meaning: "to collect information in order to produce something", difficulty: 3 },
  { word: "comprehensive", meaning: "complete and including everything", difficulty: 3 },
  { word: "conceal", meaning: "to hide", difficulty: 3 },
  { word: "conclude", meaning: "to bring to an end", difficulty: 3 },
  { word: "concur", meaning: "to agree", difficulty: 3 },
  { word: "confer", meaning: "to discuss something with others", difficulty: 3 },
  { word: "confine", meaning: "to keep within limits", difficulty: 3 },
  { word: "confirm", meaning: "to establish the truth of something", difficulty: 3 },
  { word: "conflict", meaning: "a serious disagreement or argument", difficulty: 3 },
  { word: "conform", meaning: "to comply with rules or standards", difficulty: 3 },
  { word: "contemplate", meaning: "to think about deeply", difficulty: 3 },
  { word: "contradict", meaning: "to assert the opposite of", difficulty: 3 },
  { word: "contribute", meaning: "to give in order to help achieve something", difficulty: 3 },
  { word: "convey", meaning: "to communicate", difficulty: 3 },
  { word: "convince", meaning: "to persuade", difficulty: 3 },
  { word: "core", meaning: "the central part of something", difficulty: 3 },
  { word: "criteria", meaning: "standards by which something may be judged", difficulty: 3 },
  { word: "crucial", meaning: "of great importance", difficulty: 3 },
  { word: "debate", meaning: "a formal discussion", difficulty: 3 },
  { word: "deduce", meaning: "to reach a conclusion by reasoning", difficulty: 3 },
  { word: "deficient", meaning: "not having enough of something", difficulty: 3 },
  { word: "define", meaning: "to state or describe the exact meaning", difficulty: 3 },
  { word: "demonstrate", meaning: "to show clearly", difficulty: 3 },
  { word: "denote", meaning: "to represent or mean something", difficulty: 3 },
  { word: "depict", meaning: "to describe or show", difficulty: 3 },
  { word: "derive", meaning: "to obtain from a source", difficulty: 3 },
  { word: "designate", meaning: "to appoint to a position", difficulty: 3 },
  { word: "deteriorate", meaning: "to become worse", difficulty: 3 },
  { word: "devise", meaning: "to invent or plan", difficulty: 3 },
  { word: "dimension", meaning: "an aspect or feature", difficulty: 3 },
  { word: "disclose", meaning: "to reveal", difficulty: 3 },
  { word: "discrete", meaning: "separate and distinct", difficulty: 3 },
  { word: "displace", meaning: "to take the place of", difficulty: 3 },
  { word: "disseminate", meaning: "to spread widely", difficulty: 3 },
  { word: "distinct", meaning: "clearly different", difficulty: 3 },
  { word: "distort", meaning: "to twist out of shape", difficulty: 3 },
  { word: "diverse", meaning: "showing a great deal of variety", difficulty: 3 },
  { word: "document", meaning: "a written or printed record", difficulty: 3 },
  { word: "domain", meaning: "an area of knowledge or activity", difficulty: 3 },
  { word: "dominant", meaning: "most important or powerful", difficulty: 3 },
  { word: "draft", meaning: "a preliminary version of a piece of writing", difficulty: 3 },
  { word: "drastic", meaning: "likely to have a strong or far-reaching effect", difficulty: 3 },
  { word: "duration", meaning: "the length of time something lasts", difficulty: 3 },
  { word: "elaborate", meaning: "detailed and complicated", difficulty: 3 },
  { word: "eliminate", meaning: "to remove", difficulty: 3 },
  { word: "emerge", meaning: "to come into view", difficulty: 3 },
  { word: "emphasis", meaning: "special importance or value", difficulty: 3 },
  { word: "enable", meaning: "to make possible", difficulty: 3 },
  { word: "encounter", meaning: "to meet unexpectedly", difficulty: 3 },
  { word: "enhance", meaning: "to improve", difficulty: 3 },
  { word: "ensure", meaning: "to make certain", difficulty: 3 },
  { word: "entity", meaning: "something that exists", difficulty: 3 },
  { word: "equivalent", meaning: "equal in value or meaning", difficulty: 3 },
  { word: "evaluate", meaning: "to assess", difficulty: 3 },
  { word: "evident", meaning: "clearly seen or understood", difficulty: 3 },
  { word: "aberration", meaning: "a departure from what is normal or expected", difficulty: 4 },
  { word: "abhor", meaning: "to regard with disgust and hatred", difficulty: 4 },
  { word: "acquiesce", meaning: "to accept something reluctantly but without protest", difficulty: 4 },
  { word: "alacrity", meaning: "brisk and cheerful readiness", difficulty: 4 },
  { word: "amiable", meaning: "having a friendly and pleasant manner", difficulty: 4 },
  { word: "anomaly", meaning: "something that deviates from what is standard or expected", difficulty: 4 },
  { word: "antithesis", meaning: "a contrast or opposition between two things", difficulty: 4 },
  { word: "apathetic", meaning: "showing or feeling no interest or concern", difficulty: 4 },
  { word: "arcane", meaning: "understood by few; mysterious or secret", difficulty: 4 },
  { word: "avarice", meaning: "extreme greed for wealth or material gain", difficulty: 4 },
  { word: "banal", meaning: "lacking in originality; obvious and boring", difficulty: 4 },
  { word: "belligerent", meaning: "hostile and aggressive", difficulty: 4 },
  { word: "benevolent", meaning: "well meaning and kindly", difficulty: 4 },
  { word: "boisterous", meaning: "noisy, energetic, and cheerful", difficulty: 4 },
  { word: "brazen", meaning: "bold and without shame", difficulty: 4 },
  { word: "brevity", meaning: "concise and exact use of words", difficulty: 4 },
  { word: "cacophony", meaning: "a harsh, discordant mixture of sounds", difficulty: 4 },
  { word: "candor", meaning: "the quality of being open and honest", difficulty: 4 },
  { word: "capitulate", meaning: "to surrender or give in", difficulty: 4 },
  { word: "circumspect", meaning: "wary and unwilling to take risks", difficulty: 4 },
  { word: "clandestine", meaning: "kept secret or done secretively", difficulty: 4 },
  { word: "coerce", meaning: "to persuade someone by force or threats", difficulty: 4 },
  { word: "coherent", meaning: "logical and consistent", difficulty: 4 },
  { word: "complacent", meaning: "showing smug or uncritical satisfaction", difficulty: 4 },
  { word: "concur", meaning: "to agree", difficulty: 4 },
  { word: "copious", meaning: "abundant in supply or quantity", difficulty: 4 },
  { word: "credulous", meaning: "having too great a readiness to believe things", difficulty: 4 },
  { word: "cursory", meaning: "hasty and not thorough", difficulty: 4 },
  { word: "daunting", meaning: "seeming difficult to deal with", difficulty: 4 },
  { word: "debilitate", meaning: "to make weak or infirm", difficulty: 4 },
  { word: "decorum", meaning: "behavior in keeping with good taste", difficulty: 4 },
  { word: "deference", meaning: "humble submission and respect", difficulty: 4 },
  { word: "deleterious", meaning: "causing harm or damage", difficulty: 4 },
  { word: "delineate", meaning: "describe or portray in detail", difficulty: 4 },
  { word: "demure", meaning: "reserved, modest, and shy", difficulty: 4 },
  { word: "denigrate", meaning: "to criticize unfairly", difficulty: 4 },
  { word: "deride", meaning: "to ridicule or mock", difficulty: 4 },
  { word: "despot", meaning: "a ruler with absolute power and authority", difficulty: 4 },
  { word: "detrimental", meaning: "tending to cause harm", difficulty: 4 },
  { word: "diatribe", meaning: "a forceful verbal attack", difficulty: 4 },
  { word: "didactic", meaning: "intended to teach", difficulty: 4 },
  { word: "dilatory", meaning: "slow to act", difficulty: 4 },
  { word: "disdain", meaning: "the feeling that something is unworthy of respect", difficulty: 4 },
  { word: "disparate", meaning: "essentially different in kind", difficulty: 4 },
  { word: "dissent", meaning: "to disagree", difficulty: 4 },
  { word: "dissuade", meaning: "to persuade not to do something", difficulty: 4 },
  { word: "divisive", meaning: "tending to cause disagreement", difficulty: 4 },
  { word: "dogmatic", meaning: "inclined to lay down principles as true", difficulty: 4 },
  { word: "ebullient", meaning: "cheerful and full of energy", difficulty: 4 },
  { word: "eclectic", meaning: "deriving ideas from a broad range of sources", difficulty: 4 },
  { word: "egregious", meaning: "outstandingly bad", difficulty: 4 },
  { word: "elated", meaning: "ecstatically happy", difficulty: 4 },
  { word: "elicit", meaning: "to evoke or draw out", difficulty: 4 },
  { word: "emulate", meaning: "to imitate with the effort to equal or surpass", difficulty: 4 },
  { word: "enervate", meaning: "to weaken", difficulty: 4 },
  { word: "engender", meaning: "to cause or give rise to", difficulty: 4 },
  { word: "ephemeral", meaning: "lasting for a very short time", difficulty: 4 },
  { word: "equanimity", meaning: "mental calmness", difficulty: 4 },
  { word: "equivocate", meaning: "to use ambiguous language", difficulty: 4 },
  { word: "esoteric", meaning: "intended for or understood by a small number", difficulty: 4 },
  { word: "eulogy", meaning: "a speech in praise of someone", difficulty: 4 },
  { word: "evanescent", meaning: "quickly fading or disappearing", difficulty: 4 },
  { word: "exacerbate", meaning: "to make worse", difficulty: 4 },
  { word: "exculpate", meaning: "to show that someone is not guilty", difficulty: 4 },
  { word: "exigent", meaning: "pressing; demanding", difficulty: 4 },
  { word: "exonerate", meaning: "to free from blame", difficulty: 4 },
  { word: "expedite", meaning: "to make something happen sooner", difficulty: 4 },
  { word: "fallacious", meaning: "based on mistaken belief", difficulty: 4 },
  { word: "fastidious", meaning: "very attentive to detail", difficulty: 4 },
  { word: "fatuous", meaning: "silly and pointless", difficulty: 4 },
  { word: "florid", meaning: "having a red or flushed complexion", difficulty: 4 },
  { word: "fractious", meaning: "irritable and quarrelsome", difficulty: 4 },
  { word: "furtive", meaning: "attempting to avoid notice", difficulty: 4 },
  { word: "garish", meaning: "obtrusively bright and showy", difficulty: 4 },
  { word: "garrulous", meaning: "excessively talkative", difficulty: 4 },
  { word: "gratuitous", meaning: "unnecessary or uncalled for", difficulty: 4 },
  { word: "gregarious", meaning: "fond of company", difficulty: 4 },
  { word: "hackneyed", meaning: "lacking significance through overuse", difficulty: 4 },
  { word: "hapless", meaning: "unfortunate", difficulty: 4 },
  { word: "harangue", meaning: "a lengthy and aggressive speech", difficulty: 4 },
  { word: "hedonist", meaning: "a person devoted to pleasure", difficulty: 4 },
  { word: "iconoclast", meaning: "a person who attacks cherished beliefs", difficulty: 4 },
  { word: "idiosyncrasy", meaning: "a mode of behavior unique to an individual", difficulty: 4 },
  { word: "ignominious", meaning: "deserving public shame", difficulty: 4 },
  { word: "impecunious", meaning: "having little or no money", difficulty: 4 },
  { word: "impetuous", meaning: "acting quickly without thought", difficulty: 4 },
  { word: "impudent", meaning: "not showing due respect", difficulty: 4 },
  { word: "inane", meaning: "silly or stupid", difficulty: 4 },
  { word: "inchoate", meaning: "just begun and not fully formed", difficulty: 4 },
  { word: "indolent", meaning: "wanting to avoid activity", difficulty: 4 },
  { word: "ineffable", meaning: "too great to be expressed in words", difficulty: 4 },
  { word: "inimical", meaning: "tending to obstruct or harm", difficulty: 4 },
  { word: "insipid", meaning: "lacking flavor or interest", difficulty: 4 },
  { word: "abstruse", meaning: "difficulty to understand; obscure", difficulty: 5 },
  { word: "anachronistic", meaning: "belonging to a period other than that being portrayed", difficulty: 5 },
  { word: "antipathy", meaning: "a deep-seated feeling of aversion", difficulty: 5 },
  { word: "apocryphal", meaning: "of doubtful authenticity, although widely circulated as being true", difficulty: 5 },
  { word: "assiduous", meaning: "showing great care and perseverance", difficulty: 5 },
  { word: "bellicose", meaning: "demonstrating aggression and willingness to fight", difficulty: 5 },
  { word: "blandishment", meaning: "a flattering or pleasing statement or action used to persuade", difficulty: 5 },
  { word: "cachinnate", meaning: "to laugh loudly or immoderately", difficulty: 5 },
  { word: "calumny", meaning: "the making of false and defamatory statements", difficulty: 5 },
  { word: "capricious", meaning: "given to sudden and unaccountable changes of mood or behavior", difficulty: 5 },
  { word: "circumlocution", meaning: "the use of many words where fewer would do", difficulty: 5 },
  { word: "concatenation", meaning: "a series of interconnected things or events", difficulty: 5 },
  { word: "conflagration", meaning: "an extensive fire which destroys a great deal", difficulty: 5 },
  { word: "contumacious", meaning: "stubbornly or willfully disobedient to authority", difficulty: 5 },
  { word: "corpulent", meaning: "excessively fat", difficulty: 5 },
  { word: "cupidity", meaning: "greed for money or possessions", difficulty: 5 },
  { word: "defenestration", meaning: "the action of throwing someone out of a window", difficulty: 5 },
  { word: "deleterious", meaning: "causing harm or damage", difficulty: 5 },
  { word: "demagogue", meaning: "a political leader who seeks support by appealing to desires and prejudices", difficulty: 5 },
  { word: "desuetude", meaning: "a state of disuse", difficulty: 5 },
  { word: "diaphanous", meaning: "light, delicate, and translucent", difficulty: 5 },
  { word: "didactic", meaning: "intended to teach, particularly with a moral lesson", difficulty: 5 },
  { word: "diffident", meaning: "modest or shy because of a lack of self-confidence", difficulty: 5 },
  { word: "dissemble", meaning: "conceal one's true motives, feelings, or beliefs", difficulty: 5 },
  { word: "effulgent", meaning: "shining brightly; radiant", difficulty: 5 },
  { word: "egregious", meaning: "outstandingly bad; shocking", difficulty: 5 },
  { word: "enervate", meaning: "to weaken or drain of energy", difficulty: 5 },
  { word: "ephemeral", meaning: "lasting for a very short time", difficulty: 5 },
  { word: "epistolary", meaning: "relating to the writing of letters", difficulty: 5 },
  { word: "equanimity", meaning: "mental calmness and composure", difficulty: 5 },
  { word: "execrable", meaning: "extremely bad or unpleasant", difficulty: 5 },
  { word: "excoriate", meaning: "to criticize severely", difficulty: 5 },
  { word: "expurgate", meaning: "remove matter thought to be objectionable", difficulty: 5 },
  { word: "extirpate", meaning: "to root out and destroy completely", difficulty: 5 },
  { word: "farrago", meaning: "a confused mixture", difficulty: 5 },
  { word: "feckless", meaning: "lacking initiative or strength of character", difficulty: 5 },
  { word: "filibuster", meaning: "an action such as a prolonged speech that obstructs progress", difficulty: 5 },
  { word: "fulsome", meaning: "excessive and insincere praise", difficulty: 5 },
  { word: "garrulous", meaning: "excessively talkative", difficulty: 5 },
  { word: "grandiloquent", meaning: "pompous or extravagant in language", difficulty: 5 },
  { word: "gregarious", meaning: "fond of company; sociable", difficulty: 5 },
  { word: "heterodox", meaning: "not conforming with accepted standards or beliefs", difficulty: 5 },
  { word: "iconoclast", meaning: "a person who attacks cherished beliefs", difficulty: 5 },
  { word: "impecunious", meaning: "having little or no money", difficulty: 5 },
  { word: "inchoate", meaning: "just begun and so not fully formed", difficulty: 5 },
  { word: "inimical", meaning: "tending to obstruct or harm", difficulty: 5 },
  { word: "insouciant", meaning: "showing a casual lack of concern", difficulty: 5 },
  { word: "invective", meaning: "insulting, abusive, or highly critical language", difficulty: 5 },
  { word: "jejune", meaning: "naive, simplistic, and superficial", difficulty: 5 },
  { word: "lachrymose", meaning: "tearful or given to weeping", difficulty: 5 },
  { word: "limpid", meaning: "completely clear", difficulty: 5 },
  { word: "loquacious", meaning: "tending to talk a great deal", difficulty: 5 },
  { word: "lugubrious", meaning: "looking or sounding sad and dismal", difficulty: 5 },
  { word: "mendacious", meaning: "not telling the truth; lying", difficulty: 5 },
  { word: "meretricious", meaning: "apparently attractive but having no real value", difficulty: 5 },
  { word: "misanthrope", meaning: "a person who dislikes humankind", difficulty: 5 },
  { word: "nugatory", meaning: "of no value or importance", difficulty: 5 },
  { word: "obdurate", meaning: "stubbornly refusing to change one's opinion", difficulty: 5 },
  { word: "obfuscate", meaning: "render obscure or unintelligible", difficulty: 5 },
  { word: "obstreperous", meaning: "noisy and difficulty to control", difficulty: 5 },
  { word: "opprobrium", meaning: "harsh criticism or censure", difficulty: 5 },
  { word: "ossify", meaning: "turn into bone or bony tissue; become rigid", difficulty: 5 },
  { word: "panacea", meaning: "a solution or remedy for all difficultyies", difficulty: 5 },
  { word: "parsimony", meaning: "extreme unwillingness to spend money", difficulty: 5 },
  { word: "pellucid", meaning: "transparently clear", difficulty: 5 },
  { word: "penurious", meaning: "extremely poor; poverty-stricken", difficulty: 5 },
  { word: "perfidy", meaning: "deceitfulness; untrustworthiness", difficulty: 5 },
  { word: "perspicacious", meaning: "having a ready insight into and understanding of things", difficulty: 5 },
  { word: "phlegmatic", meaning: "having an unemotional and stolidly calm disposition", difficulty: 5 },
  { word: "prevaricate", meaning: "speak or act in an evasive way", difficulty: 5 },
  { word: "prolix", meaning: "using or containing too many words", difficulty: 5 },
  { word: "propinquity", meaning: "the state of being close to someone or something", difficulty: 5 },
  { word: "puerile", meaning: "childishly silly and trivial", difficulty: 5 },
  { word: "pulchritude", meaning: "beauty", difficulty: 5 },
  { word: "quixotic", meaning: "exceedingly idealistic; unrealistic and impractical", difficulty: 5 },
  { word: "recalcitrant", meaning: "having an obstinately uncooperative attitude", difficulty: 5 },
  { word: "recondite", meaning: "little known; abstruse", difficulty: 5 },
  { word: "redolent", meaning: "strongly reminiscent or suggestive of", difficulty: 5 },
  { word: "sagacious", meaning: "having keen mental discernment and good judgment", difficulty: 5 },
  { word: "salubrious", meaning: "health-giving; healthy", difficulty: 5 },
  { word: "sanguine", meaning: "optimistic or positive, especially in a bad situation", difficulty: 5 },
  { word: "scurrilous", meaning: "making or spreading scandalous claims", difficulty: 5 },
  { word: "sesquipedalian", meaning: "characterized by long words; long-winded", difficulty: 5 },
  { word: "somnolent", meaning: "sleepy; drowsy", difficulty: 5 },
  { word: "spurious", meaning: "not being what it purports to be; false", difficulty: 5 },
  { word: "stentorian", meaning: "loud and powerful", difficulty: 5 },
  { word: "supercilious", meaning: "behaving as though one is superior", difficulty: 5 },
  { word: "sycophant", meaning: "a person who acts obsequiously toward someone important", difficulty: 5 },
  { word: "taciturn", meaning: "reserved or uncommunicative", difficulty: 5 },
  { word: "tenebrous", meaning: "dark; shadowy", difficulty: 5 },
  { word: "trenchant", meaning: "vigorous or incisive in expression or style", difficulty: 5 },
  { word: "turbid", meaning: "cloudy, opaque, or thick with suspended matter", difficulty: 5 },
  { word: "ubiquitous", meaning: "present, appearing, or found everywhere", difficulty: 5 },
  { word: "vicissitude", meaning: "a change of circumstances or fortune", difficulty: 5 },
  { word: "vituperative", meaning: "bitter and abusive", difficulty: 5 }
];

// Export the type for type safety
export type VocabularyWord = typeof VOCABULARY_WORDS[number]; 